app:
  title: Ben's IDP Portal
  baseUrl: ${BASE_URL}

backend:
  baseUrl: ${BASE_URL}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  # config options: https://node-postgres.com/apis/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

integrations:
  gitlab:
    - host: gitlab.home.rottlr.de
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://gitlab.home.rottlr.de/api/v4

auth:
  environment: homelab
  providers:
    gitlab:
      homelab:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
        audience: https://gitlab.home.rottlr.de
        sessionDuration: { hours: 4 }
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

kubernetes:
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: Homelab
          authProvider: 'serviceAccount'

catalog:
  providers:
    gitlab:
      yourProviderId:
        # https://backstage.io/docs/integrations/gitlab/discovery
        host: gitlab.home.rottlr.de
        branch: main
        group: idp
        schedule:
          frequency: { minutes: 30 }
          timeout: { minutes: 3 }
        # https://backstage.io/docs/integrations/gitlab/org
        orgEnabled: true
        relations:
          - INHERITED
          - SHARED_FROM_GROUPS
        rules:
          - allow: [Group, User]
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
